const profiles = [
  {
    id: 1,
    name: "Anjali Sharma",
    age: 25,
    gender: "Female",
    religion: "Hindu",
    caste: "Brahmin",
    country: "Nepal",
    city: "Kathmandu",
    education: "MBA",
    profession: "Marketing Manager",
    income: "800,000 NPR/year",
    maritalStatus: "Never Married",
    height: "5'4\"",
    skinTone: "Fair",
    hobbies: ["Reading", "Dancing"],
    profileImage: "https://randomuser.me/api/portraits/women/10.jpg"
  },
  {
    id: 2,
    name: "Rohan Karki",
    age: 28,
    gender: "Male",
    religion: "Hindu",
    caste: "Chhetri",
    country: "Nepal",
    city: "Pokhara",
    education: "Engineering",
    profession: "Software Developer",
    income: "1,200,000 NPR/year",
    maritalStatus: "Never Married",
    height: "5'9\"",
    skinTone: "Medium",
    hobbies: ["Hiking", "Photography"],
    profileImage: "https://randomuser.me/api/portraits/men/1.jpg"
  },
  {
    id: 3,
    name: "Priya Gurung",
    age: 24,
    gender: "Female",
    religion: "Buddhist",
    caste: "Gurung",
    country: "Nepal",
    city: "Dharan",
    education: "BBA",
    profession: "Accountant",
    income: "600,000 NPR/year",
    maritalStatus: "Never Married",
    height: "5'2\"",
    skinTone: "Light Brown",
    hobbies: ["Singing", "Cooking"],
    profileImage: "https://randomuser.me/api/portraits/women/12.jpg"
  },
  {
    id: 4,
    name: "Suresh Rai",
    age: 30,
    gender: "Male",
    religion: "Hindu",
    caste: "Rai",
    country: "Nepal",
    city: "Birgunj",
    education: "MSc",
    profession: "Teacher",
    income: "500,000 NPR/year",
    maritalStatus: "Never Married",
    height: "5'7\"",
    skinTone: "Wheatish",
    hobbies: ["Football", "Writing"],
    profileImage: "https://randomuser.me/api/portraits/men/3.jpg"
  },
  {
    id: 5,
    name: "Bina Magar",
    age: 22,
    gender: "Female",
    religion: "Christian",
    caste: "Magar",
    country: "Nepal",
    city: "Butwal",
    education: "BSc Nursing",
    profession: "Nurse",
    income: "550,000 NPR/year",
    maritalStatus: "Never Married",
    height: "5'3\"",
    skinTone: "Medium Fair",
    hobbies: ["Painting", "Volunteering"],
    profileImage: "https://randomuser.me/api/portraits/women/15.jpg"
  },
  {
    id: 6,
    name: "Amit Joshi",
    age: 32,
    gender: "Male",
    religion: "Hindu",
    caste: "Brahmin",
    country: "Nepal",
    city: "Bharatpur",
    education: "PhD",
    profession: "Professor",
    income: "900,000 NPR/year",
    maritalStatus: "Divorced",
    height: "5'8\"",
    skinTone: "Fair",
    hobbies: ["Research", "Chess"],
    profileImage: "https://randomuser.me/api/portraits/men/5.jpg"
  },
  {
    id: 7,
    name: "Sunita Thapa",
    age: 27,
    gender: "Female",
    religion: "Hindu",
    caste: "Thakuri",
    country: "Nepal",
    city: "Hetauda",
    education: "LLB",
    profession: "Lawyer",
    income: "1,100,000 NPR/year",
    maritalStatus: "Never Married",
    height: "5'5\"",
    skinTone: "Fair",
    hobbies: ["Debating", "Traveling"],
    profileImage: "https://randomuser.me/api/portraits/women/18.jpg"
  },
  {
    id: 8,
    name: "Prakash Yadav",
    age: 29,
    gender: "Male",
    religion: "Hindu",
    caste: "Yadav",
    country: "Nepal",
    city: "Janakpur",
    education: "BCom",
    profession: "Businessman",
    income: "1,500,000 NPR/year",
    maritalStatus: "Never Married",
    height: "5'10\"",
    skinTone: "Dark",
    hobbies: ["Cricket", "Politics"],
    profileImage: "https://randomuser.me/api/portraits/men/7.jpg"
  },
  {
    id: 9,
    name: "Mina Tamang",
    age: 23,
    gender: "Female",
    religion: "Buddhist",
    caste: "Tamang",
    country: "Nepal",
    city: "Dhading",
    education: "BA",
    profession: "Social Worker",
    income: "400,000 NPR/year",
    maritalStatus: "Never Married",
    height: "5'1\"",
    skinTone: "Light Brown",
    hobbies: ["Dancing", "Community Service"],
    profileImage: "https://randomuser.me/api/portraits/women/20.jpg"
  },
  {
    id: 10,
    name: "Rajesh Newar",
    age: 31,
    gender: "Male",
    religion: "Buddhist",
    caste: "Newar",
    country: "Nepal",
    city: "Bhaktapur",
    education: "BArch",
    profession: "Architect",
    income: "1,300,000 NPR/year",
    maritalStatus: "Never Married",
    height: "5'11\"",
    skinTone: "Medium",
    hobbies: ["Drawing", "Traditional Music"],
    profileImage: "https://randomuser.me/api/portraits/men/9.jpg"
  },
  {
    id: 11,
    name: "Sita Poudel",
    age: 26,
    gender: "Female",
    religion: "Hindu",
    caste: "Brahmin",
    country: "Nepal",
    city: "Nepalgunj",
    education: "MEd",
    profession: "Teacher",
    income: "650,000 NPR/year",
    maritalStatus: "Never Married",
    height: "5'3\"",
    skinTone: "Fair",
    hobbies: ["Poetry", "Gardening"],
    profileImage: "https://randomuser.me/api/portraits/women/22.jpg"
  },
  {
    id: 12,
    name: "Hari Basnet",
    age: 33,
    gender: "Male",
    religion: "Hindu",
    caste: "Chhetri",
    country: "Nepal",
    city: "Dhangadhi",
    education: "MSc IT",
    profession: "IT Consultant",
    income: "1,400,000 NPR/year",
    maritalStatus: "Married",
    height: "5'9\"",
    skinTone: "Wheatish",
    hobbies: ["Coding", "Gaming"],
    profileImage: "https://randomuser.me/api/portraits/men/11.jpg"
  },
  {
    id: 13,
    name: "Gita Limbu",
    age: 24,
    gender: "Female",
    religion: "Hindu",
    caste: "Limbu",
    country: "Nepal",
    city: "Ilam",
    education: "BSc Agriculture",
    profession: "Agriculture Officer",
    income: "700,000 NPR/year",
    maritalStatus: "Never Married",
    height: "5'2\"",
    skinTone: "Medium Fair",
    hobbies: ["Tea Gardening", "Singing"],
    profileImage: "https://randomuser.me/api/portraits/women/24.jpg"
  },
  {
    id: 14,
    name: "Niraj Bista",
    age: 29,
    gender: "Male",
    religion: "Hindu",
    caste: "Brahmin",
    country: "Nepal",
    city: "Mahendranagar",
    education: "CA",
    profession: "Chartered Accountant",
    income: "1,600,000 NPR/year",
    maritalStatus: "Never Married",
    height: "5'8\"",
    skinTone: "Fair",
    hobbies: ["Stock Market", "Reading"],
    profileImage: "https://randomuser.me/api/portraits/men/13.jpg"
  },
  {
    id: 15,
    name: "Rina KC",
    age: 27,
    gender: "Female",
    religion: "Hindu",
    caste: "Chhetri",
    country: "Nepal",
    city: "Pokhara",
    education: "BHM",
    profession: "Hotel Manager",
    income: "850,000 NPR/year",
    maritalStatus: "Never Married",
    height: "5'4\"",
    skinTone: "Fair",
    hobbies: ["Traveling", "Cooking"],
    profileImage: "https://randomuser.me/api/portraits/women/26.jpg"
  },
  {
    id: 16,
    name: "Bikram Singh",
    age: 34,
    gender: "Male",
    religion: "Hindu",
    caste: "Thakuri",
    country: "Nepal",
    city: "Surkhet",
    education: "LLM",
    profession: "Judge",
    income: "1,800,000 NPR/year",
    maritalStatus: "Married",
    height: "5'10\"",
    skinTone: "Wheatish",
    hobbies: ["Reading", "Horse Riding"],
    profileImage: "https://randomuser.me/api/portraits/men/15.jpg"
  },
  {
    id: 17,
    name: "Pooja Maharjan",
    age: 23,
    gender: "Female",
    religion: "Buddhist",
    caste: "Newar",
    country: "Nepal",
    city: "Lalitpur",
    education: "BFA",
    profession: "Artist",
    income: "500,000 NPR/year",
    maritalStatus: "Never Married",
    height: "5'1\"",
    skinTone: "Light Brown",
    hobbies: ["Painting", "Sculpting"],
    profileImage: "https://randomuser.me/api/portraits/women/28.jpg"
  },
  {
    id: 18,
    name: "Dipesh Rana",
    age: 30,
    gender: "Male",
    religion: "Hindu",
    caste: "Chhetri",
    country: "Nepal",
    city: "Chitwan",
    education: "BSc Forestry",
    profession: "Forest Officer",
    income: "750,000 NPR/year",
    maritalStatus: "Never Married",
    height: "5'9\"",
    skinTone: "Medium",
    hobbies: ["Wildlife Photography", "Hiking"],
    profileImage: "https://randomuser.me/api/portraits/men/17.jpg"
  },
  {
    id: 19,
    name: "Sabina Ghale",
    age: 25,
    gender: "Female",
    religion: "Buddhist",
    caste: "Ghale",
    country: "Nepal",
    city: "Gorkha",
    education: "BSc",
    profession: "Lab Technician",
    income: "600,000 NPR/year",
    maritalStatus: "Never Married",
    height: "5'3\"",
    skinTone: "Medium Fair",
    hobbies: ["Singing", "Trekking"],
    profileImage: "https://randomuser.me/api/portraits/women/30.jpg"
  },
  {
    id: 20,
    name: "Arjun Thapa",
    age: 35,
    gender: "Male",
    religion: "Hindu",
    caste: "Thakuri",
    country: "Nepal",
    city: "Biratnagar",
    education: "MD",
    profession: "Doctor",
    income: "1,500,000 NPR/year",
    maritalStatus: "Divorced",
    height: "5'10\"",
    skinTone: "Wheatish",
    hobbies: ["Travelling", "Chess"],
    profileImage: "https://randomuser.me/api/portraits/men/19.jpg"
  },
  // Continuing with 30 more objects...
  {
    id: 21,
    name: "Anita Dhital",
    age: 24,
    gender: "Female",
    religion: "Hindu",
    caste: "Brahmin",
    country: "Nepal",
    city: "Kathmandu",
    education: "BSc CSIT",
    profession: "Web Developer",
    income: "700,000 NPR/year",
    maritalStatus: "Never Married",
    height: "5'2\"",
    skinTone: "Fair",
    hobbies: ["Coding", "Blogging"],
    profileImage: "https://randomuser.me/api/portraits/women/32.jpg"
  },
  {
    id: 22,
    name: "Sagar Pandey",
    age: 28,
    gender: "Male",
    religion: "Hindu",
    caste: "Brahmin",
    country: "Nepal",
    city: "Butwal",
    education: "MBA",
    profession: "Bank Manager",
    income: "1,100,000 NPR/year",
    maritalStatus: "Never Married",
    height: "5'8\"",
    skinTone: "Fair",
    hobbies: ["Finance", "Badminton"],
    profileImage: "https://randomuser.me/api/portraits/men/21.jpg"
  },
  {
    id: 23,
    name: "Laxmi Pariyar",
    age: 26,
    gender: "Female",
    religion: "Hindu",
    caste: "Dalit",
    country: "Nepal",
    city: "Nawalparasi",
    education: "BEd",
    profession: "Teacher",
    income: "550,000 NPR/year",
    maritalStatus: "Never Married",
    height: "5'1\"",
    skinTone: "Dark",
    hobbies: ["Social Work", "Singing"],
    profileImage: "https://randomuser.me/api/portraits/women/34.jpg"
  },
  {
    id: 24,
    name: "Bibek Acharya",
    age: 31,
    gender: "Male",
    religion: "Hindu",
    caste: "Brahmin",
    country: "Nepal",
    city: "Kathmandu",
    education: "PhD Physics",
    profession: "Scientist",
    income: "1,300,000 NPR/year",
    maritalStatus: "Married",
    height: "5'9\"",
    skinTone: "Fair",
    hobbies: ["Research", "Astronomy"],
    profileImage: "https://randomuser.me/api/portraits/men/23.jpg"
  },
  {
    id: 25,
    name: "Saraswati Sapkota",
    age: 22,
    gender: "Female",
    religion: "Hindu",
    caste: "Brahmin",
    country: "Nepal",
    city: "Pokhara",
    education: "BBA",
    profession: "Entrepreneur",
    income: "900,000 NPR/year",
    maritalStatus: "Never Married",
    height: "5'3\"",
    skinTone: "Fair",
    hobbies: ["Business", "Yoga"],
    profileImage: "https://randomuser.me/api/portraits/women/36.jpg"
  },
  {
    id: 26,
    name: "Kiran Adhikari",
    age: 29,
    gender: "Male",
    religion: "Hindu",
    caste: "Chhetri",
    country: "Nepal",
    city: "Dharan",
    education: "BDS",
    profession: "Dentist",
    income: "1,200,000 NPR/year",
    maritalStatus: "Never Married",
    height: "5'10\"",
    skinTone: "Medium",
    hobbies: ["Swimming", "Music"],
    profileImage: "https://randomuser.me/api/portraits/men/25.jpg"
  },
  {
    id: 27,
    name: "Rekha Bhandari",
    age: 27,
    gender: "Female",
    religion: "Hindu",
    caste: "Chhetri",
    country: "Nepal",
    city: "Hetauda",
    education: "BSc Nursing",
    profession: "Nurse",
    income: "650,000 NPR/year",
    maritalStatus: "Never Married",
    height: "5'4\"",
    skinTone: "Medium Fair",
    hobbies: ["Reading", "Dancing"],
    profileImage: "https://randomuser.me/api/portraits/women/38.jpg"
  },
  {
    id: 28,
    name: "Prabin Subedi",
    age: 32,
    gender: "Male",
    religion: "Hindu",
    caste: "Brahmin",
    country: "Nepal",
    city: "Janakpur",
    education: "MSc Environment",
    profession: "Environmentalist",
    income: "850,000 NPR/year",
    maritalStatus: "Never Married",
    height: "5'8\"",
    skinTone: "Fair",
    hobbies: ["Nature Conservation", "Photography"],
    profileImage: "https://randomuser.me/api/portraits/men/27.jpg"
  },
  {
    id: 29,
    name: "Muna Lama",
    age: 23,
    gender: "Female",
    religion: "Buddhist",
    caste: "Lama",
    country: "Nepal",
    city: "Solukhumbu",
    education: "BA",
    profession: "Tour Guide",
    income: "500,000 NPR/year",
    maritalStatus: "Never Married",
    height: "5'0\"",
    skinTone: "Light Brown",
    hobbies: ["Trekking", "Mountaineering"],
    profileImage: "https://randomuser.me/api/portraits/women/40.jpg"
  },
  {
    id: 30,
    name: "Santosh Khadka",
    age: 34,
    gender: "Male",
    religion: "Hindu",
    caste: "Khadka",
    country: "Nepal",
    city: "Dhankuta",
    education: "BSc Agriculture",
    profession: "Agriculture Expert",
    income: "750,000 NPR/year",
    maritalStatus: "Married",
    height: "5'7\"",
    skinTone: "Dark",
    hobbies: ["Farming", "Traditional Music"],
    profileImage: "https://randomuser.me/api/portraits/men/29.jpg"
  },
  {
    id: 31,
    name: "Asha Malla",
    age: 25,
    gender: "Female",
    religion: "Hindu",
    caste: "Malla",
    country: "Nepal",
    city: "Patan",
    education: "BBA",
    profession: "HR Manager",
    income: "800,000 NPR/year",
    maritalStatus: "Never Married",
    height: "5'2\"",
    skinTone: "Fair",
    hobbies: ["Event Management", "Dancing"],
    profileImage: "https://randomuser.me/api/portraits/women/42.jpg"
  },
  {
    id: 32,
    name: "Nabin Shrestha",
    age: 30,
    gender: "Male",
    religion: "Buddhist",
    caste: "Shrestha",
    country: "Nepal",
    city: "Bhaktapur",
    education: "BArch",
    profession: "Interior Designer",
    income: "1,000,000 NPR/year",
    maritalStatus: "Never Married",
    height: "5'9\"",
    skinTone: "Medium",
    hobbies: ["Designing", "Traditional Art"],
    profileImage: "https://randomuser.me/api/portraits/men/31.jpg"
  },
  {
    id: 33,
    name: "Binita BK",
    age: 24,
    gender: "Female",
    religion: "Hindu",
    caste: "Dalit",
    country: "Nepal",
    city: "Rolpa",
    education: "BEd",
    profession: "Teacher",
    income: "500,000 NPR/year",
    maritalStatus: "Never Married",
    height: "5'1\"",
    skinTone: "Dark",
    hobbies: ["Teaching", "Social Work"],
    profileImage: "https://randomuser.me/api/portraits/women/44.jpg"
  },
  {
    id: 34,
    name: "Rajendra Raut",
    age: 35,
    gender: "Male",
    religion: "Hindu",
    caste: "Raut",
    country: "Nepal",
    city: "Sarlahi",
    education: "MA Economics",
    profession: "Economist",
    income: "1,100,000 NPR/year",
    maritalStatus: "Married",
    height: "5'8\"",
    skinTone: "Wheatish",
    hobbies: ["Economic Research", "Politics"],
    profileImage: "https://randomuser.me/api/portraits/men/33.jpg"
  },
  {
    id: 35,
    name: "Sangita Sunuwar",
    age: 26,
    gender: "Female",
    religion: "Hindu",
    caste: "Sunuwar",
    country: "Nepal",
    city: "Ramechhap",
    education: "BSc Forestry",
    profession: "Forest Guard",
    income: "600,000 NPR/year",
    maritalStatus: "Never Married",
    height: "5'2\"",
    skinTone: "Medium Fair",
    hobbies: ["Nature Conservation", "Singing"],
    profileImage: "https://randomuser.me/api/portraits/women/46.jpg"
  },
  {
    id: 36,
    name: "Dinesh Danuwar",
    age: 28,
    gender: "Male",
    religion: "Hindu",
    caste: "Danuwar",
    country: "Nepal",
    city: "Sindhuli",
    education: "BCom",
    profession: "Accountant",
    income: "700,000 NPR/year",
    maritalStatus: "Never Married",
    height: "5'7\"",
    skinTone: "Dark",
    hobbies: ["Music", "Fishing"],
    profileImage: "https://randomuser.me/api/portraits/men/35.jpg"
  },
  {
    id: 37,
    name: "Pramila Tharu",
    age: 23,
    gender: "Female",
    religion: "Hindu",
    caste: "Tharu",
    country: "Nepal",
    city: "Chitwan",
    education: "BA",
    profession: "Social Activist",
    income: "450,000 NPR/year",
    maritalStatus: "Never Married",
    height: "5'0\"",
    skinTone: "Dark",
    hobbies: ["Dancing", "Social Work"],
    profileImage: "https://randomuser.me/api/portraits/women/48.jpg"
  },
  {
    id: 38,
    name: "Bikash Gharti",
    age: 31,
    gender: "Male",
    religion: "Hindu",
    caste: "Gharti",
    country: "Nepal",
    city: "Pyuthan",
    education: "BSc",
    profession: "Agriculture Technician",
    income: "650,000 NPR/year",
    maritalStatus: "Married",
    height: "5'6\"",
    skinTone: "Dark",
    hobbies: ["Farming", "Local Politics"],
    profileImage: "https://randomuser.me/api/portraits/men/37.jpg"
  },
  {
    id: 39,
    name: "Sabitri Kumal",
    age: 24,
    gender: "Female",
    religion: "Hindu",
    caste: "Kumal",
    country: "Nepal",
    city: "Nawalparasi",
    education: "BEd",
    profession: "Teacher",
    income: "500,000 NPR/year",
    maritalStatus: "Never Married",
    height: "5'1\"",
    skinTone: "Medium",
    hobbies: ["Pottery", "Singing"],
    profileImage: "https://randomuser.me/api/portraits/women/50.jpg"
  },
  {
    id: 40,
    name: "Yogesh Majhi",
    age: 29,
    gender: "Male",
    religion: "Hindu",
    caste: "Majhi",
    country: "Nepal",
    city: "Tanahu",
    education: "BSc",
    profession: "Fisheries Officer",
    income: "700,000 NPR/year",
    maritalStatus: "Never Married",
    height: "5'7\"",
    skinTone: "Dark",
    hobbies: ["Fishing", "Boating"],
    profileImage: "https://randomuser.me/api/portraits/men/39.jpg"
  },
  {
    id: 41,
    name: "Goma Sarki",
    age: 26,
    gender: "Female",
    religion: "Hindu",
    caste: "Sarki",
    country: "Nepal",
    city: "Gulmi",
    education: "BA",
    profession: "Tailor",
    income: "400,000 NPR/year",
    maritalStatus: "Never Married",
    height: "5'0\"",
    skinTone: "Dark",
    hobbies: ["Sewing", "Singing"],
    profileImage: "https://randomuser.me/api/portraits/women/51.jpg"
  },
  {
    id: 42,
    name: "Ramesh Damai",
    age: 32,
    gender: "Male",
    religion: "Hindu",
    caste: "Damai",
    country: "Nepal",
    city: "Kaski",
    education: "BA Music",
    profession: "Musician",
    income: "600,000 NPR/year",
    maritalStatus: "Married",
    height: "5'6\"",
    skinTone: "Medium",
    hobbies: ["Music", "Instrument Making"],
    profileImage: "https://randomuser.me/api/portraits/men/41.jpg"
  },
  {
    id: 43,
    name: "Sita Kami",
    age: 22,
    gender: "Female",
    religion: "Hindu",
    caste: "Kami",
    country: "Nepal",
    city: "Lamjung",
    education: "10+2",
    profession: "Blacksmith",
    income: "350,000 NPR/year",
    maritalStatus: "Never Married",
    height: "5'0\"",
    skinTone: "Dark",
    hobbies: ["Metal Work", "Crafting"],
    profileImage: "https://randomuser.me/api/portraits/women/53.jpg"
  },
  {
    id: 44,
    name: "Hari Badi",
    age: 36,
    gender: "Male",
    religion: "Hindu",
    caste: "Badi",
    country: "Nepal",
    city: "Banke",
    education: "Intermediate",
    profession: "Musician",
    income: "300,000 NPR/year",
    maritalStatus: "Married",
    height: "5'5\"",
    skinTone: "Dark",
    hobbies: ["Music", "Cultural Preservation"],
    profileImage: "https://randomuser.me/api/portraits/men/43.jpg"
  },
  {
    id: 45,
    name: "Radha Giri",
    age: 28,
    gender: "Female",
    religion: "Hindu",
    caste: "Giri",
    country: "Nepal",
    city: "Palpa",
    education: "BA",
    profession: "Social Worker",
    income: "450,000 NPR/year",
    maritalStatus: "Never Married",
    height: "5'2\"",
    skinTone: "Medium",
    hobbies: ["Community Service", "Reading"],
    profileImage: "https://randomuser.me/api/portraits/women/55.jpg"
  },
  {
    id: 46,
    name: "Bishnu Lohar",
    age: 33,
    gender: "Male",
    religion: "Hindu",
    caste: "Lohar",
    country: "Nepal",
    city: "Rupandehi",
    education: "Diploma",
    profession: "Metal Worker",
    income: "500,000 NPR/year",
    maritalStatus: "Married",
    height: "5'7\"",
    skinTone: "Dark",
    hobbies: ["Metal Crafting", "Farming"],
    profileImage: "https://randomuser.me/api/portraits/men/45.jpg"
  },
  {
    id: 47,
    name: "Gita Chhetri",
    age: 25,
    gender: "Female",
    religion: "Hindu",
    caste: "Chhetri",
    country: "Nepal",
    city: "Kailali",
    education: "BSc",
    profession: "Health Worker",
    income: "550,000 NPR/year",
    maritalStatus: "Never Married",
    height: "5'3\"",
    skinTone: "Medium Fair",
    hobbies: ["Health Awareness", "Dancing"],
    profileImage: "https://randomuser.me/api/portraits/women/57.jpg"
  },
  {
    id: 48,
    name: "Narayan Roka",
    age: 40,
    gender: "Male",
    religion: "Hindu",
    caste: "Roka",
    country: "Nepal",
    city: "Dolpa",
    education: "Intermediate",
    profession: "Farmer",
    income: "300,000 NPR/year",
    maritalStatus: "Married",
    height: "5'6\"",
    skinTone: "Dark",
    hobbies: ["Farming", "Local Politics"],
    profileImage: "https://randomuser.me/api/portraits/men/47.jpg"
  },
  {
    id: 49,
    name: "Saraswati Thakali",
    age: 27,
    gender: "Female",
    religion: "Hindu",
    caste: "Thakali",
    country: "Nepal",
    city: "Mustang",
    education: "BHM",
    profession: "Hotel Owner",
    income: "1,200,000 NPR/year",
    maritalStatus: "Never Married",
    height: "5'2\"",
    skinTone: "Medium Fair",
    hobbies: ["Cooking", "Business"],
    profileImage: "https://randomuser.me/api/portraits/women/59.jpg"
  },
  {
    id: 50,
    name: "Krishna Sherpa",
    age: 35,
    gender: "Male",
    religion: "Buddhist",
    caste: "Sherpa",
    country: "Nepal",
    city: "Solukhumbu",
    education: "Mountaineering Course",
    profession: "Mountain Guide",
    income: "1,500,000 NPR/year",
    maritalStatus: "Married",
    height: "5'8\"",
    skinTone: "Dark",
    hobbies: ["Mountaineering", "Tourism"],
    profileImage: "https://randomuser.me/api/portraits/men/49.jpg"
  }
];

const id = document.querySelector(".id");
profiles.forEach(profile => {
  id.innerHTML += `
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 mb-4">
      <div class="card h-100 shadow-sm">
        <div class="position-relative">
          <img src="${profile.profileImage}" 
               class="card-img-top" 
               alt="${profile.name}" 
               style="height: 180px; object-fit: cover;">
          <span class="position-absolute bottom-0 start-0 bg-primary text-white px-2 py-1 small">
            ${profile.age} yrs
          </span>
        </div>
        <div class="card-body p-3">
          <h5 class="card-title mb-1">${profile.name}</h5>
          <p class="text-muted small mb-2">
            <i class="fas fa-hotel text-primary me-1"></i> ${profile.profession}
          </p>
          <div class="d-flex justify-content-between small">
            <span><i class="fas fa-map-marker-alt text-muted me-1"></i> ${profile.city}</span>
            <span class="badge bg-light text-dark">${profile.religion}</span>
          </div>
        </div>
        <div class="card-footer bg-white border-0 pt-0">
          <button class="btn btn-sm btn-outline-primary w-100" onclick="window.location.href='profile-page.html'">
            View Profile
          </button>
        </div>
      </div>
    </div>
  `;
});

